### ISSUE TITLE
Database requirement is not met

### ISSUE THREAD

**Issue by Rxbsxn** [Easiv/CoolWriter-backend#2]
>Setup rails project (Look how to create rails project for RAILS API, with PSQL DB).

You didn't change the default DB adapter, please change it to psql
![screen shot 2018-09-07 at 14 12 50](https://user-images.githubusercontent.com/17426143/45218569-5d0a3500-b2a8-11e8-9823-3435586234d1.png)

**Comment by Easiv** [comment]
Done

**Comment by Rxbsxn** [comment]
#3
